# For more information: https://laravel.com/docs/sail
version: '3'
services:
    nginx:
        image: nginx:1.21-alpine
        container_name: makemewatch_nginx
        restart: unless-stopped
        tty: true
        ports:
            - "${FORWARD_HTTP_PORT:-80}:80"
            - "${FORWARD_HTTPS_PORT:-443}:443"
        working_dir: /var/www/html
        volumes:
            - '.:/var/www/html:ro'
            - './.docker/nginx/conf.d/:/etc/nginx/conf.d/:ro'
        networks:
            - makemewatch
    app:
        build:
          context: .
          args:
            - 'WWWGROUP=${WWWGROUP}'
            - 'WWWUSER=${WWWUSER}'
        image: thomasdom/makemewatch-php:1.0.0
        container_name: makemewatch_app
        restart: unless-stopped
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - '.:/var/www/html'
        user: '${WWWUSER}:${WWWGROUP}'
        networks:
            - makemewatch
        depends_on:
            - mysql
    mysql:
        image: 'mysql/mysql-server:8.0'
        container_name: makemewatch_mysql
        restart: unless-stopped
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_RANDOM_ROOT_PASSWORD: yes
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - makemewatch
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p", "${DB_PASSWORD}"]
            retries: 3
            timeout: 5s

networks:
    makemewatch:
        driver: bridge
volumes:
    mysql:
        driver: local
